Group17_MVC/Group17_MVC/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Group17_MVC.Controllers
{
    public class AdminController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Logout()
        {
            
            
            return RedirectToAction("Index", "Home");
        }

    }
}

Group17_MVC/Group17_MVC/Controllers/QuanlidonhangController.cs
using Group17_MVC;
using System.Linq;
using System.Web.Mvc;

namespace Group17_MVC.Controllers
{
    public class QuanlidonhangController : Controller
    {
        private readonly Nhom17_WedBanSachEntities db = new Nhom17_WedBanSachEntities();

        public ActionResult Index(string searchString)
        {
            var donHangs = string.IsNullOrEmpty(searchString)
                ? db.DonHangs.ToList()
                : db.DonHangs.Where(d => d.MaDonHang.Contains(searchString)).ToList();

            return View(donHangs);
        }

       
        public JsonResult ChiTietDonHang(string maDonHang)
        {
            if (string.IsNullOrEmpty(maDonHang))
            {
                return Json(new { error = "Mã đơn hàng không hợp lệ." }, JsonRequestBehavior.AllowGet);
            }

            var orderDetails = db.ChiTietDonHangs
                                 .Where(c => c.MaDonHang == maDonHang)
                                 .Select(c => new
                                 {
                                     MaDonHang = c.MaDonHang,
                                     NguoiDung = c.DonHang.NguoiDung.HoTen,
                                     ChiTiet = c.DonHang.ChiTietDonHangs.Select(d => new
                                     {
                                         MaSach = d.MaSach,
                                         TenSach = d.Sach.TenSach,
                                         TacGia = d.Sach.TacGia,
                                         SoLuong = d.SoLuong,
                                         GiaBan = d.GiaBan
                                     }).ToList(),
                                     TongTien = c.DonHang.TongTien
                                 })
                                 .FirstOrDefault();

            if (orderDetails == null)
            {
                return Json(new { error = "Không tìm thấy đơn hàng." }, JsonRequestBehavior.AllowGet);
            }

            return Json(orderDetails, JsonRequestBehavior.AllowGet);
        }
    }
}

Group17_MVC/Group17_MVC/Controllers/QuanlinguoidungController.cs
using Group17_MVC;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Group17_MVC.Controllers
{
    public class QuanlinguoidungController : Controller
    {
        Nhom17_WedBanSachEntities db = new Nhom17_WedBanSachEntities();
        private static readonly HashSet<string> lockedAccounts = new HashSet<string>();

        public static HashSet<string> GetLockedAccounts()
        {
            return lockedAccounts;
        }

        public ActionResult LockAccount(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                lockedAccounts.Add(id);
            }
            return RedirectToAction("Index");
        }

        public ActionResult UnlockAccount(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                lockedAccounts.Remove(id);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Index(string searchString)
        {
            var nguoidung = string.IsNullOrEmpty(searchString)
                ? db.NguoiDungs.ToList()
                : db.NguoiDungs.Where(d =>
                    d.MaNguoiDung.Contains(searchString) ||
                    d.HoTen.Contains(searchString) ||
                    d.Email.Contains(searchString) ||
                    d.SoDienThoai.Contains(searchString)).ToList();
            ViewBag.LockedAccounts = lockedAccounts;
            ViewBag.SearchString = searchString;
            return View(nguoidung);
        }

        public ActionResult Edit(string id)
        {
            var item = db.NguoiDungs.FirstOrDefault(n => n.MaNguoiDung == id);
            if (item == null)
            {
                return HttpNotFound();
            }

            var roles = new List<SelectListItem>
            {
                new SelectListItem { Text = "Admin", Value = "Admin" },
                new SelectListItem { Text = "KhachHang", Value = "KhachHang" }
            };
            ViewBag.VaiTroList = roles;

            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NguoiDung model)
        {
            if (ModelState.IsValid)
            {
                var user = db.NguoiDungs.FirstOrDefault(u => u.MaNguoiDung == model.MaNguoiDung);
                if (user != null)
                {
                    user.VaiTro = model.VaiTro;
                    db.Entry(user).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        public ActionResult Add()
        {
            
            var roles = new List<SelectListItem>
    {
        new SelectListItem { Text = "Admin", Value = "Admin" },
        new SelectListItem { Text = "KhachHang", Value = "KhachHang" }
    };
            ViewBag.VaiTroList = roles;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(NguoiDung model)
        {
            if (ModelState.IsValid)
            {
                db.NguoiDungs.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(model);
        }

    }
}

Group17_MVC/Group17_MVC/Controllers/QuanlisanphamController.cs
using Group17_MVC;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Group17_MVC.Controllers
{
    public class QuanlisanphamController : Controller
    {
        // GET: Admin/Quanlisanpham
        private Nhom17_WedBanSachEntities db = new Nhom17_WedBanSachEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Add()
        {
            using (var context = new Nhom17_WedBanSachEntities())
            {
                var theLoaiList = context.TheLoais
                                     .Select(tl => new SelectListItem
                                     {
                                         Value = tl.MaTheLoai.ToString(),
                                         Text = tl.MaTheLoai.ToString()
                                     }).ToList();

                ViewBag.TheLoaiList = theLoaiList;
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Sach model)
        {
            if (ModelState.IsValid)
            {
                model.NgayTao = DateTime.Now;
                db.Saches.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);

        }
        public ActionResult Edit(string id)
        {
            
            var categories = db.TheLoais.ToList();
            ViewBag.TheLoaiList = new SelectList(categories, "MaTheLoai", "TenTheLoai");
            var item = db.Saches.FirstOrDefault(s => s.MaSach == id);

            if (item == null)
            {
                return HttpNotFound();
            }

            return View(item); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Sach model)
        {
            if (ModelState.IsValid)
            {
                
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var categories = db.TheLoais.ToList();
            ViewBag.TheLoaiList = new SelectList(categories, "MaTheLoai", "TenTheLoai");

            return View(model);
        }
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var item = db.Saches.FirstOrDefault(s => s.MaSach == id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            var item = db.Saches.FirstOrDefault(s => s.MaSach == id);
            if (item == null)
            {
                return HttpNotFound();
            }
            db.Saches.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Group17_MVC/Group17_MVC/Controllers/ThongkeController.cs
using Group17_MVC;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Group17_MVC.Controllers
{
    public class ThongKeController : Controller
    {
        private Nhom17_WedBanSachEntities db = new Nhom17_WedBanSachEntities();

        public ActionResult Index(string searchQuery)
        {
            int tongnguoidung = db.NguoiDungs.Count();
            ViewBag.Tonguser = tongnguoidung;
            int tongdonhang = db.DonHangs.Count();
            ViewBag.Tongdh = tongdonhang;
            int sachchuadat = db.Saches.Where(s => !s.ChiTietDonHangs.Any()).Count();
            ViewBag.SachChuaDat = sachchuadat;

            var listsach = db.Saches
                .Where(s => !s.ChiTietDonHangs.Any())
                .Select(s => new SachViewModel
                {
                    MaSach = s.MaSach,
                    TenSach = s.TenSach
                });

            if (!string.IsNullOrEmpty(searchQuery))
            {
                listsach = listsach.Where(s => s.MaSach.Contains(searchQuery));
            }

            return View(listsach.ToList());
        }

    }

    public class SachViewModel
    {
        public string MaSach { get; set; }
        public string TenSach { get; set; }
    }
}

Group17_MVC/Group17_MVC/Views/Thongke/Index.cshtml
@model List<Group17_MVC.Controllers.SachViewModel>
@{
    ViewBag.Title = "Thống kê";
   
}
@section naviheader {
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="@Url.Action("Index", "Admin")" Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="@Url.Action("Index", "Quanlisanpham")" Quản lí sản phẩm</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="@Url.Action("Index", "Quanlinguoidung")" Quản lí người dùng</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="@Url.Action("Index", "Quanlidonhang")" Quản lí đơn hàng</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="@Url.Action("Index", "ThongKe")" Thống kê</a>
        </li>
    </ul>
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Thống kê</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Thống kê</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: system-ui, -apple-system, sans-serif;
        }

        .dashboard {
            padding: 2rem;
            min-height: 100vh;
            background: #f9fafb;
        }

        .stats-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 1.5rem;
            margin-bottom: 2rem;
        }

        .stat-card {
            padding: 1.5rem;
            border-radius: 0.75rem;
            color: white;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s ease;
        }

            .stat-card:hover {
                transform: scale(1.02);
            }

            .stat-card.yellow {
                background: linear-gradient(to right, #fbbf24, #f59e0b);
            }

            .stat-card.orange {
                background: linear-gradient(to right, #fb923c, #f97316);
            }

            .stat-card.blue {
                background: linear-gradient(to right, #22d3ee, #06b6d4);
            }

        .stat-content {
            display: flex;
            align-items: center;
            gap: 1rem;
        }

        .icon-wrapper {
            background: rgba(255, 255, 255, 0.2);
            padding: 0.75rem;
            border-radius: 0.5rem;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .stat-info h3 {
            font-size: 1.875rem;
            font-weight: bold;
            margin-bottom: 0.25rem;
        }

        .stat-info p {
            font-size: 0.875rem;
            opacity: 0.9;
        }

        .content-section {
            background: white;
            border-radius: 0.75rem;
            padding: 1.5rem;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        }

        .search-bar {
            display: flex;
            gap: 1rem;
            margin-bottom: 1.5rem;
            align-items: center;
        }

        .search-input-wrapper {
            position: relative;
            flex: 1;
        }

        .search-input {
            width: 100%;
            padding: 0.75rem 1rem;
            padding-right: 2.5rem;
            border: 1px solid #e5e7eb;
            border-radius: 0.5rem;
            outline: none;
            transition: all 0.2s;
        }

            .search-input:focus {
                border-color: #3b82f6;
                box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.1);
            }

        .search-input-wrapper svg {
            position: absolute;
            right: 10px;
            top: 50%;
            transform: translateY(-50%);
            color: #9ca3af;
        }

        .refresh-button {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            padding: 0.5rem 1.25rem;
            background: #3b82f6;
            color: white;
            border: none;
            border-radius: 0.5rem;
            cursor: pointer;
            transition: background-color 0.2s;
            white-space: nowrap; 
        }

            .refresh-button:hover {
                background: #2563eb;
            }


        .data-table {
            width: 100%;
            border-collapse: collapse;
            border: 1px solid #e5e7eb;
            border-radius: 0.5rem;
            overflow: hidden;
        }

            .data-table th {
                background: #f9fafb;
                padding: 1rem 1.5rem;
                text-align: left;
                font-size: 0.875rem;
                color: #4b5563;
                border-bottom: 1px solid #e5e7eb;
            }

            .data-table td {
                padding: 1rem 1.5rem;
                font-size: 0.875rem;
                color: #4b5563;
                border-bottom: 1px solid #e5e7eb;
            }

            .data-table tr:hover {
                background: #f9fafb;
            }

            .data-table tbody tr:last-child td {
                border-bottom: none;
            }
    </style>
</head>
<body>
    <div class="dashboard">
        <div class="stats-grid">
            <div class="stat-card yellow">
                <div class="stat-content">
                    <div class="icon-wrapper">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <rect x="2" y="3" width="20" height="14" rx="2" ry="2"></rect>
                            <line x1="8" y1="21" x2="16" y2="21"></line>
                            <line x1="12" y1="17" x2="12" y2="21"></line>
                        </svg>
                    </div>
                    <div class="stat-info">
                        <h3>@ViewBag.SachChuaDat</h3>
                        <p>Sách chưa đặt</p>
                    </div>
                </div>
            </div>

            <div class="stat-card orange">
                <div class="stat-content">
                    <div class="icon-wrapper">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M3 3h18v13H3z"></path>
                            <path d="M21 16V8h3v8h-3z"></path>
                        </svg>
                    </div>
                    <div class="stat-info">
                        <h3>@ViewBag.Tongdh</h3>
                        <p>Đơn hàng</p>
                    </div>
                </div>
            </div>

            <div class="stat-card blue">
                <div class="stat-content">
                    <div class="icon-wrapper">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                            <circle cx="12" cy="7" r="4"></circle>
                        </svg>
                    </div>
                    <div class="stat-info">
                        <h3>@ViewBag.Tonguser</h3>
                        <p>Tài khoản người dùng</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="content-section">
            <form method="get" action="@Url.Action("Index", "ThongKe")">
                <div class="search-bar">
                    <div class="search-input-wrapper">
                        <input type="text" name="searchQuery" placeholder="Tìm kiếm theo mã sách" class="search-input" />
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <circle cx="11" cy="11" r="8"></circle>
                            <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
                        </svg>
                    </div>
                    <button type="submit" class="search-button" style="background-color: #28a745; border: 1px solid #28a745; color: white; padding: 8px 16px; font-size: 16px; display: flex; align-items: center; border-radius: 12px;">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="margin-right: 8px;">
                            <circle cx="11" cy="11" r="8" />
                            <line x1="16" y1="16" x2="22" y2="22" />
                        </svg>
                        Tìm kiếm
                    </button>


                    <button type="button" onclick="window.location.href='@Url.Action("Index", "ThongKe")'" class="refresh-button">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <path d="M23 4v6h-6"></path>
                            <path d="M1 20v-6h6"></path>
                            <path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10"></path>
                            <path d="M1 14l4.64 4.36A9 9 0 0 0 20.49 15"></path>
                        </svg>
                        Làm mới
                    </button>
                </div>
            </form>

            <table class="data-table">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Mã sách</th>
                        <th>Tên sách</th>
                        <th>Trạng thái</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        int stt = 1;
                        foreach (var book in Model)
                        {
                            <tr>
                                <td>@stt</td>
                                <td>@book.MaSach</td>
                                <td>@book.TenSach</td>
                                <td>CD</td>
                            </tr>
                            stt++;
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>